"""Biological assembly generated from one deposited protein structure."""

import gemmi
import numpy as np

from pathlib import Path


class BiologicalAssembly:
    """Own one generated assembly and expose its protein and DNA components."""

    def __init__(
        self,
        source     : gemmi.Structure,
        model      : gemmi.Model,
        assembly_id: str,
    ) -> None:
        """Bind a generated model to its deposited structure and assembly name.

        Args:
            source: Complete deposited Gemmi structure containing the original chains.
            model: Model generated by applying the named biological-assembly operations.
            assembly_id: Exact assembly identifier declared by the deposition.
        """
        self.source      = source
        self.model       = model
        self.assembly_id = assembly_id

    def protein_copy(
        self,
        chain_name: str,
        copy_index: int,
    ) -> tuple[gemmi.Chain, gemmi.Chain]:
        """Resolve a deposited protein chain and one transformed assembly copy.

        Args:
            chain_name: Complete deposited chain name. Multi-character names remain one
                chain and are never split into characters.
            copy_index: One-based occurrence among generated peptide chains sharing the name.

        Returns:
            Deposited chain followed by the selected transformed assembly copy.

        Raises:
            ValueError: If the deposited peptide chain or requested copy is absent.
        """
        deposited = self.source[0].find_chain(chain_name)
        if deposited is None or not self.is_protein(deposited):
            raise ValueError(f"protein chain {chain_name!r} is absent")

        copies = [
            chain
            for chain in self.model
            if chain.name == chain_name and self.is_protein(chain)
        ]
        if copy_index < 1 or copy_index > len(copies):
            raise ValueError(
                f"chain {chain_name!r} requests copy {copy_index}, "
                f"but assembly {self.assembly_id!r} contains {len(copies)}"
            )

        return deposited, copies[copy_index - 1]

    def protein_chains(self) -> tuple[gemmi.Chain, ...]:
        """Return every peptide chain in the generated assembly.

        Returns:
            Ordered tuple of chains classified by Gemmi as L- or D-peptides.
        """
        return tuple(chain for chain in self.model if self.is_protein(chain))

    def dna_chains(self) -> tuple[gemmi.Chain, ...]:
        """Return every DNA polymer chain in the generated assembly.

        Returns:
            Ordered tuple of chains classified by Gemmi as DNA polymers.
        """
        return tuple(chain for chain in self.model if self.is_dna(chain))

    def dna_atoms(self) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Extract occupied DNA heavy atoms and the chain owning each atom.

        Hydrogen atoms and atoms with non-positive occupancy are excluded. Coordinates and
        van der Waals radii remain in ångströms. Owner indices refer to :meth:`dna_chains` order.

        Returns:
            Coordinate matrix ``float64 [D,3]``, van der Waals radii ``float64 [D]``, and
            DNA-chain owner indices ``int64 [D]``.

        Raises:
            ValueError: If an occupied heavy atom has non-finite coordinates or no positive
                van der Waals radius.
        """
        positions: list[tuple[float, float, float]] = []
        radii    : list[float]                      = []
        owners   : list[int]                        = []

        for chain_index, chain in enumerate(self.dna_chains()):
            for residue in chain.get_polymer().first_conformer():
                for atom in residue.first_conformer():
                    if atom.element.atomic_number <= 1 or atom.occ <= 0.0:
                        continue

                    position = (
                        float(atom.pos.x),
                        float(atom.pos.y),
                        float(atom.pos.z),
                    )
                    radius = float(atom.element.vdw_r)
                    if not np.isfinite(position).all() or radius <= 0.0:
                        raise ValueError(
                            f"DNA chain {chain.name!r} contains an invalid heavy atom"
                        )

                    positions.append(position)
                    radii.append(radius)
                    owners.append(chain_index)

        return (
            np.asarray(positions, dtype=np.float64).reshape((-1, 3)),
            np.asarray(radii, dtype=np.float64),
            np.asarray(owners, dtype=np.int64),
        )

    def write_protein_copy(
        self,
        target    : Path,
        chain_name: str,
        copy_index: int,
        identifier: str,
    ) -> None:
        """Write one selected protein copy as a protein-only Foldseek mmCIF.

        Args:
            target: Destination mmCIF path managed by LambdaForge.
            chain_name: Complete deposited protein-chain name.
            copy_index: One-based generated assembly copy.
            identifier: Logical protein identifier stored as the structure name.

        Raises:
            ValueError: If the requested protein copy does not exist.
            OSError: If the mmCIF file cannot be written.
        """
        _, chain     = self.protein_copy(chain_name, copy_index)
        selected      = gemmi.Structure()
        selected.name = identifier
        model         = gemmi.Model(1)

        model.add_chain(chain.clone())
        selected.add_model(model)
        selected.setup_entities()

        target.parent.mkdir(parents=True, exist_ok=True)
        selected.make_mmcif_document().write_file(str(target))

    def is_protein(self, chain: gemmi.Chain) -> bool:
        """Return whether Gemmi classifies a chain as a peptide polymer.

        Args:
            chain: Gemmi chain from the deposited or generated model.

        Returns:
            ``True`` for L- and D-peptide polymers; otherwise ``False``.
        """
        polymer = chain.get_polymer()
        return bool(polymer) and polymer.check_polymer_type() in {
            gemmi.PolymerType.PeptideL,
            gemmi.PolymerType.PeptideD,
        }

    def is_dna(self, chain: gemmi.Chain) -> bool:
        """Return whether Gemmi classifies a chain as a DNA polymer.

        Args:
            chain: Gemmi chain from the generated assembly.

        Returns:
            ``True`` only for DNA polymers; RNA and peptide chains return ``False``.
        """
        polymer = chain.get_polymer()
        return bool(polymer) and polymer.check_polymer_type() == gemmi.PolymerType.Dna
